name: build-docs

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"
          enable-cache: true

      - name: Install dependencies
        run: |
          uv venv --python 3.13
          uv pip install mkdocs mkdocs-material

      - name: Deploy docs
        run: uv run mkdocs gh-deploy --force
