name: build-docs

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.13"
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
            uv.lock
          ignore-nothing-to-cache: true

      - name: Install docs dependencies
        run: |
          uv sync --extra docs --python 3.13 --locked

      - name: Deploy docs
        run: uv run mkdocs gh-deploy --force
