name: build-docs

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.13"
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
            setup.py
          ignore-nothing-to-cache: true

      - name: Install dependencies
        run: |
          uv venv .venv --python 3.13 --clear
          uv pip install mkdocs mkdocs-material

      - name: Deploy docs
        run: uv run mkdocs gh-deploy --force
